create table if not exists users(
	id int generated by default as identity primary key,
	username varchar,
	password varchar, 
	role varchar,
	bank int
);

create table if not exists items(
	id int generated by default as identity primary key,
	name varchar,
	price int
);

create table if not exists orders(
	id int generated by default as identity primary key,
	user_id int references users(id),
	item_id int references items(id)
	status varchar
);


create table if not exists stats(
	id int generated by default as identity primary key,
	items_sold int,
	revenue int
);

insert into stats (items_sold, revenue) values (0,0);